[workspace]
members = ["packages/*", "modules/*"]

[profile.release.package.types]
codegen-units = 1
incremental = false

[profile.release.package.wallet]
codegen-units = 1
incremental = false

[profile.release.package.rpc]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false