[package]
name = "cosm-signer"
version = "0.1.0"
authors = ["bragaz <leo.braga95@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tonic = { version = "0.4.0"}
prost = { version = "0.7.0"}
wasm-bindgen = { version = "0.2.70", features = ["serde-serialize"]}
wasm-bindgen-test = "0.3.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.62" }
reqwest = { version = "0.11.0", features = ["blocking", "json"]}
cosmos-sdk-proto = { version = "0.3.0"}
cosmos-tx = { version = "0.2.0-pre" }
anomaly = { version = "0.2.0" }
thiserror = { version = "1.0.22" }

[dev-dependencies]
actix-rt = "2.0.2"

[build-dependencies]
tonic-build = "0.4.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true