[package]
name = "wallet"
version = "0.1.0"
authors = ["bragaz <leo.braga95@gmail.com"]
edition = "2018"
license = "Apache 2.0"
repository = "https://github.com/forbole/cosmos-key-signer"

[lib]
crate-type = ["cdylib"]

[dependencies]
types = { path = "../../packages/types", version = "0.1.0"}
bitcoin = { version = "0.26.0" }
bech32 = { version = "0.8.0" }
cosmos-sdk-proto = { version = "0.3.0"}
hdpath = {version = "0.6.0", features = ["with-bitcoin"] }
k256 = { version = "0.7.2", features = ["ecdsa-core", "ecdsa", "sha256"]}
prost = { version = "0.7.0"}
prost-types = {version = "0.7"}
ripemd160 = { version = "0.9.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.62" }
sha2 = { version = "0.9.3" }
thiserror = { version = "1.0.22" }
tiny-bip39 = { version = "0.8.0" }
wasm-bindgen = { version = "0.2.70", features = ["serde-serialize"]}
wasm-bindgen-futures = { version = "0.4.21"}
wasm-bindgen-test = "0.3.20"